version: '3'
services:
  facturaexpress_app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - facturaexpress_db
  facturaexpress_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  facturaexpress_admin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - facturaexpress_db
